### ISSUE TITLE
Feature request: Rails 5 support.

### ISSUE THREAD

**Issue by JorgeDDW** [locomotivecms/engine#1189]

**Comment by aeberlin** [comment]
I'm also interested in this. Starting working on a few of the dependencies this morning.

@did, see https://github.com/locomotivecms/custom_fields/pull/36

**Comment by azeemh** [comment]
would like to see this happen

**Comment by b264** [comment]
I almost didn't use locomotive because of this...

**Comment by JacobEvelyn** [comment]
Yeah we're going to have to migrate away from Locomotive unless this gets added, given that [Locomotive's version of Rails](https://github.com/locomotivecms/engine/blob/master/locomotive_cms.gemspec#L21) is soon to be [entirely unsupported for even critical Rails security patches](http://rubyonrails.org/security/).

**Comment by did** [comment]
@JacobEvelyn fair enough. FYI, we're actively working on it. Our test suit passes but we've got minor issues here and there. Our goal is to launch the Engine 3.4 running Rails 5.1 by the end of this month.

**Comment by JacobEvelyn** [comment]
@did thanks so much for the update! Really appreciate the transparency.

**Comment by JacobEvelyn** [comment]
@did any updates on this?

**Comment by did** [comment]
@JacobEvelyn, we made some tests the new engine running Rails 5.1, more specifically, we tested the new engine with our hosting platform and it seemed to be all good. So now, we need more people to test it :-)

**Comment by toreyheinz** [comment]
I'll give it a try.

**Comment by JacobEvelyn** [comment]
Cool, we'll start working on this soon and let you know how it works for us! 😄

**Comment by toreyheinz** [comment]
Readme says Mongoid '~> 6.4.0', but the gemspec says '~> 6.3.0'
https://github.com/locomotivecms/engine/blob/master/locomotivecms.gemspec#L27

**Comment by toreyheinz** [comment]
Just upgraded my local engine from Rails '4.2.9' => '5.1.6' and Ruby from '2.3.4' => '2.5.1'. 

Needed to make a number of "normal" tweaks after `rails app:update`, but it was pretty painless.

Deployed a site to the local engine, and everything seemed to be working as expected, until I went to edit a many-to-many relationship. The dropdown/search field was not working. Looks some css/js didn’t get loaded right.

I’ll try this with a “fresh” install, and see if it’s just an issue with my setup.

**Comment by toreyheinz** [comment]
Still having the same issue with a fresh install, I'll dig into this later. Also, I'll have some updates to the readme.

**Comment by did** [comment]
thanks @toreyheinz, that's super weird, I fixed an issue this morning with the many_to_may relationship and the dropdown worked correctly. I guess there is another js issue preventing the select2 to be executed. 
What does your browser console tell you? thanks for your help!

**Comment by toreyheinz** [comment]
All I'm seeing from the console are a couple of missing css files.
<img width="1435" alt="screenshot 2018-04-03 16 35 59" src="https://user-images.githubusercontent.com/23319/38274658-66ebf7be-375d-11e8-96b4-6fc311e755ae.png">

Here's the outerHTML from inspector:
```html
<div class="row new-field">
    <div class="field col-md-10 col-xs-9">
        <select 
          name="id" 
          id="id" 
          class="form-control input" 
          data-label-method="_label" 
          data-list-url="/locomotive/canvasinnovations/content_types/images/entries.json" 
          data-placeholder="Choose one of the images" 
          data-searching="Searching..." 
          data-no-matches="No matches found" 
          data-too-short="Please enter 1 or more character" 
          data-select2-id="id" 
          tabindex="0" 
          aria-hidden="false">
        </select>
    </div>
    <div class="button col-md-2 col-xs-3 text-right">
        <a 
          class="btn btn-primary btn-sm add" 
          href="/locomotive/canvasinnovations/content_types/images/entries/show_in_form?field_id=5ac3bb76f88fbb5e0d7efdc4&amp;parent_slug=services"
        >Add</a>
      </div>
</div>
```

Seems strange that the name and ID are "id".

`http://127.0.0.1:3000/locomotive/canvasinnovations/content_types/images/entries.json` returns proper JSON

Hope that helps.

**Comment by did** [comment]
@toreyheinz thanks for the feedback. The select is okay and in the latest commit of the engine, I don't have the errors in the console.

**Comment by toreyheinz** [comment]
@did I grabbed the latest commit, and the missing CSS files are there, but my dropdown/search field is still not working. I should be able to work on this tomorrow. Thanks for all your work on this project!

**Comment by toreyheinz** [comment]
The Content-Type I'm working with has multiple many-to-many relations, and the last one was working. With another Content-Type with only one many-to-many relationship, it works fine. So the issue seems to be with having multiple selects. I'm not sure if this is because they both have the same id, or something else with select2.

![screenshot 2018-04-05 17 49 46](https://user-images.githubusercontent.com/23319/38393746-c7e6e5fe-38f9-11e8-807e-a3ec70944c29.png)


I'll keep poking at it.
